import React from 'react'

function Home() {
  return (
    <>
      <h1>Hotels Review</h1>
    <div className="container">
      <div className="post-card-line">
        {/* box start */}
        <div className="post-card-box">
          <div className="post-card-1 border-radius-10 hover-up">
            <div className="post-thumb thumb-overlay img-hover-slide position-relative">
              <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" />
            </div>
            <div className="post-content p-30">
                <div className="entry-meta meta-0 font-small mb-10">
                    <a href="category.html"><span className="post-cat text-info">Travel</span></a>
                    <a href="category.html"><span className="post-cat text-success">Food</span></a>
                </div>
                <div className="d-flex post-card-content">
                    <h5 className="post-title">
                        <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a>
                    </h5>
                    <div className="post-excerpt">
                        <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p>
                    </div>
                    <div className="entry-meta meta-1 float-left font-x-small text-uppercase">
                        <span className="post-on">27 August</span>
                        <span className="time-reading has-dot">12 mins read</span>
                        <span className="post-by has-dot">23k views</span>
                    </div>
                </div>
            </div>
          </div>
        </div>
        {/* box end */}

        {/* dummy  */}
          <div className="post-card-box"> <div className="post-card-1 border-radius-10 hover-up"> <div className="post-thumb thumb-overlay img-hover-slide position-relative"> <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" /> </div> <div className="post-content p-30"> <div className="entry-meta meta-0 font-small mb-10"> <a href="category.html"><span className="post-cat text-info">Travel</span></a> <a href="category.html"><span className="post-cat text-success">Food</span></a> </div> <div className="d-flex post-card-content"> <h5 className="post-title"> <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a> </h5> <div className="post-excerpt"> <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p> </div> <div className="entry-meta meta-1 float-left font-x-small text-uppercase"> <span className="post-on">27 August</span> <span className="time-reading has-dot">12 mins read</span> <span className="post-by has-dot">23k views</span> </div> </div> </div> </div> </div><div className="post-card-box"> <div className="post-card-1 border-radius-10 hover-up"> <div className="post-thumb thumb-overlay img-hover-slide position-relative"> <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" /> </div> <div className="post-content p-30"> <div className="entry-meta meta-0 font-small mb-10"> <a href="category.html"><span className="post-cat text-info">Travel</span></a> <a href="category.html"><span className="post-cat text-success">Food</span></a> </div> <div className="d-flex post-card-content"> <h5 className="post-title"> <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a> </h5> <div className="post-excerpt"> <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p> </div> <div className="entry-meta meta-1 float-left font-x-small text-uppercase"> <span className="post-on">27 August</span> <span className="time-reading has-dot">12 mins read</span> <span className="post-by has-dot">23k views</span> </div> </div> </div> </div> </div>
          <div className="post-card-box"> <div className="post-card-1 border-radius-10 hover-up"> <div className="post-thumb thumb-overlay img-hover-slide position-relative"> <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" /> </div> <div className="post-content p-30"> <div className="entry-meta meta-0 font-small mb-10"> <a href="category.html"><span className="post-cat text-info">Travel</span></a> <a href="category.html"><span className="post-cat text-success">Food</span></a> </div> <div className="d-flex post-card-content"> <h5 className="post-title"> <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a> </h5> <div className="post-excerpt"> <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p> </div> <div className="entry-meta meta-1 float-left font-x-small text-uppercase"> <span className="post-on">27 August</span> <span className="time-reading has-dot">12 mins read</span> <span className="post-by has-dot">23k views</span> </div> </div> </div> </div> </div><div className="post-card-box"> <div className="post-card-1 border-radius-10 hover-up"> <div className="post-thumb thumb-overlay img-hover-slide position-relative"> <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" /> </div> <div className="post-content p-30"> <div className="entry-meta meta-0 font-small mb-10"> <a href="category.html"><span className="post-cat text-info">Travel</span></a> <a href="category.html"><span className="post-cat text-success">Food</span></a> </div> <div className="d-flex post-card-content"> <h5 className="post-title"> <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a> </h5> <div className="post-excerpt"> <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p> </div> <div className="entry-meta meta-1 float-left font-x-small text-uppercase"> <span className="post-on">27 August</span> <span className="time-reading has-dot">12 mins read</span> <span className="post-by has-dot">23k views</span> </div> </div> </div> </div> </div>
          <div className="post-card-box"> <div className="post-card-1 border-radius-10 hover-up"> <div className="post-thumb thumb-overlay img-hover-slide position-relative"> <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" /> </div> <div className="post-content p-30"> <div className="entry-meta meta-0 font-small mb-10"> <a href="category.html"><span className="post-cat text-info">Travel</span></a> <a href="category.html"><span className="post-cat text-success">Food</span></a> </div> <div className="d-flex post-card-content"> <h5 className="post-title"> <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a> </h5> <div className="post-excerpt"> <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p> </div> <div className="entry-meta meta-1 float-left font-x-small text-uppercase"> <span className="post-on">27 August</span> <span className="time-reading has-dot">12 mins read</span> <span className="post-by has-dot">23k views</span> </div> </div> </div> </div> </div><div className="post-card-box"> <div className="post-card-1 border-radius-10 hover-up"> <div className="post-thumb thumb-overlay img-hover-slide position-relative"> <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" /> </div> <div className="post-content p-30"> <div className="entry-meta meta-0 font-small mb-10"> <a href="category.html"><span className="post-cat text-info">Travel</span></a> <a href="category.html"><span className="post-cat text-success">Food</span></a> </div> <div className="d-flex post-card-content"> <h5 className="post-title"> <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a> </h5> <div className="post-excerpt"> <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p> </div> <div className="entry-meta meta-1 float-left font-x-small text-uppercase"> <span className="post-on">27 August</span> <span className="time-reading has-dot">12 mins read</span> <span className="post-by has-dot">23k views</span> </div> </div> </div> </div> </div>
          <div className="post-card-box"> <div className="post-card-1 border-radius-10 hover-up"> <div className="post-thumb thumb-overlay img-hover-slide position-relative"> <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" /> </div> <div className="post-content p-30"> <div className="entry-meta meta-0 font-small mb-10"> <a href="category.html"><span className="post-cat text-info">Travel</span></a> <a href="category.html"><span className="post-cat text-success">Food</span></a> </div> <div className="d-flex post-card-content"> <h5 className="post-title"> <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a> </h5> <div className="post-excerpt"> <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p> </div> <div className="entry-meta meta-1 float-left font-x-small text-uppercase"> <span className="post-on">27 August</span> <span className="time-reading has-dot">12 mins read</span> <span className="post-by has-dot">23k views</span> </div> </div> </div> </div> </div><div className="post-card-box"> <div className="post-card-1 border-radius-10 hover-up"> <div className="post-thumb thumb-overlay img-hover-slide position-relative"> <img src="https://images.unsplash.com/photo-1647142137353-48abfbce9496?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60" /> </div> <div className="post-content p-30"> <div className="entry-meta meta-0 font-small mb-10"> <a href="category.html"><span className="post-cat text-info">Travel</span></a> <a href="category.html"><span className="post-cat text-success">Food</span></a> </div> <div className="d-flex post-card-content"> <h5 className="post-title"> <a href="single.html">Want fluffy Japanese pancakes but can’t fly to Tokyo?</a> </h5> <div className="post-excerpt"> <p>Graduating from a top accelerator or incubator can be as career-defining for a&nbsp;startup founder&nbsp;as an elite university diploma. The intensive programmes, which…</p> </div> <div className="entry-meta meta-1 float-left font-x-small text-uppercase"> <span className="post-on">27 August</span> <span className="time-reading has-dot">12 mins read</span> <span className="post-by has-dot">23k views</span> </div> </div> </div> </div> </div>
        {/* dummy  */}
      </div>
    </div>
    </>
  )
}

export default Home